---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "backend"
      provider: "fabric8"
      version: "1.0"
      group: "com.redhat.microservices"
    name: "backend"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "backend"
      provider: "fabric8"
      group: "com.redhat.microservices"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations: {}
    labels:
      project: "backend"
      provider: "fabric8"
      version: "1.0"
      group: "com.redhat.microservices"
    name: "backend"
  spec:
    replicas: 1
    selector:
      project: "backend"
      provider: "fabric8"
      version: "1.0"
      group: "com.redhat.microservices"
    template:
      metadata:
        annotations: {}
        labels:
          project: "backend"
          provider: "fabric8"
          version: "1.0"
          group: "com.redhat.microservices"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/backend:1.0"
          name: "backend"
          ports:
          - containerPort: 8080
            name: "http"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
kind: "List"
